POST http://localhost:3000/addFarm
Content-Type: application/json

{
    "location": "somewhere",
    "cage_position": "up",
    "created_at": "today",
    "status": "connected"
}

###

PUT http://localhost:3000/farm/67c8dfe807d0f8fc2fb6e2c9/update
Content-Type: application/json

{
    "status": "Disconnected"
}

###

GET http://localhost:3000/farm/67c8dfef07d0f8fc2fb6e2ca/info
Content-Type: application/json

{

}

###

GET http://localhost:3000/farm/67c8dfef07d0f8fc2fb6e2ca/check_status
Content-Type: application/json

{

}

###

GET http://localhost:3000/farm/67c8dfef07d0f8fc2fb6e2ca/getActiveSensorData
Content-Type: application/json

{

}

###

GET http://localhost:3000/farm
Content-Type: application/json

{

}

###
DELETE  http://localhost:3000/farm/67d5d7bd46aaceff4e1be9f6/delete
Content-Type: application/json

{

}