POST http://localhost:3000/addFarm
Content-Type: application/json

{
    "farm_name": "Dickie's Cool Farm 5",
    "location": "somewhere",
    "lora_passwd": "hi"
}

###

PUT http://localhost:3000/farm/67d64529e9547432429df362/update
Content-Type: application/json

{
    "farm_name": "Dickie's Cool Farm 4"
}

###

GET http://localhost:3000/farm/67d60003c103ef9612736bce/info
Content-Type: application/json

{

}

###

GET http://localhost:3000/farm/67c8dfef07d0f8fc2fb6e2ca/check_status
Content-Type: application/json

{

}

###

GET http://localhost:3000/farm/67c8dfef07d0f8fc2fb6e2ca/getActiveSensorData
Content-Type: application/json

{

}

###

GET http://localhost:3000/farm
Content-Type: application/json

{

}

###
DELETE  http://localhost:3000/farm/67dd8a42d712b4314465a9b3/delete
Content-Type: application/json

{

}