### Farm CRUD Tests
POST http://localhost:3000/addFarm
Content-Type: application/json

{
    "location": "DOWNTOWN",
    "farm_name": "Farm 5"
}

###

PUT http://localhost:3000/farm/67d8258b258731e4f2c39d1e/update
Content-Type: application/json

{
    "status": "Disconnected"
}

###

GET http://localhost:3000/farm/67c8cb6dcf6ae5ac04544ca9/info
Content-Type: application/json

{

}

###

GET http://localhost:3000/farm/67d8258b258731e4f2c39d1e/check_status
Content-Type: application/json

{
    

}

###
GET http://localhost:3000/farm
Content-Type: application/json

{

}

###
DELETE  http://localhost:3000/farm/67edd0603292ebfd25680dd2/delete
Content-Type: application/json

{

}

### Sensor Tests
GET http://localhost:3000/farm/67d8258b258731e4f2c39d1e/getActiveSensorData
Content-Type: application/json

{

}

###
POST http://localhost:3000/farm/67d8258b258731e4f2c39d1e/updateActiveSensorData
Content-Type: application/json

{
    "temperature": [
        {"timestamp": "2025-03-20", "value": 23.5}
    ],
    "height": [
        {"timestamp": "2025-03-20", "value": 12.88}
    ],
    "camera": [
        {"timestamp": "2025-03-20", "image": "https://i.pinimg.com/originals/75/f6/35/75f6354f76f157a343326cb48a0949f7.jpg"}
    ],
    "created_at": "2025-03-20"
}

###
GET http://localhost:3000/farm/67d8258b258731e4f2c39d1e/getArchivedSensorData
Content-Type: application/json
{

}

### System Level Tests
GET http://localhost:3000/farm/67d8258b258731e4f2c39d1e/getActiveSystemLevels
Content-Type: application/json

{

}

###
GET http://localhost:3000/farm/67d8258b258731e4f2c39d1e/getArchivedSystemLevels
Content-Type: application/json

{

}

### LIft Schedule Tests 
POST http://localhost:3000/farm/cage
Content-Type: application/json

{
    "ids": "67edd17ad47abf534b7b45d8",
    "command": 1,
    "max_height": 10,
    "min_height": 5
}

### All same dates and array of strings for ids and command
POST http://localhost:3000/farm/cage/schedule
Content-Type: application/json

{
    
    "ids": [
        "67dd82c0583ddb4a70757e64",
        "67edd17ad47abf534b7b45d8"
    ],
    "date": [
        {"day": "Tues", "time": "8:00"}
    ],
    "command": 1
    
}

###
GET http://localhost:3000/farm/67edd17ad47abf534b7b45d8/getActiveLiftSchedule
Content-Type: application/json

{

}

###
DELETE http://localhost:3000/farm/67dd82c0583ddb4a70757e64/deleteActiveLiftSchedule
Content-Type: application/json

{

}

###
DELETE http://localhost:3000/farm/67edd17ad47abf534b7b45d8/deleteArchiveLiftSchedule
Content-Type: application/json

{
    
}
