### Farm CRUD Tests
POST http://localhost:3000/addFarm
Content-Type: application/json

{
    "location": "VA Beach",
    "farm_name": "MONEY MAKER"
}

###

PUT http://localhost:3000/farm/67f966b2b9c6c0d234547e30/update
Content-Type: application/json

{
    "status": true,
    "farm_name": "SUPER MONEY MAKER",
    "cage_position": false 
}

###

GET http://localhost:3000/farm/67f966b2b9c6c0d234547e30/info
Content-Type: application/json

{

}

###

GET http://localhost:3000/farm/67f95e768844df15f0121f71/check_status
Content-Type: application/json

{
    

}

###
GET http://localhost:3000/farm
Content-Type: application/json

{

}

###
DELETE  http://localhost:3000/farm/67f853db547fbbf38ec4af78/delete
Content-Type: application/json

{

}

### Sensor Tests
GET http://localhost:3000/farm/68029efecb480f3fb7c499cf/getSensorData
Content-Type: application/json

{

}

###
GET http://localhost:3000/farm/68029efecb480f3fb7c499cf/getAllSensorData
Content-Type: application/json

{

}

###
GET http://localhost:3000/farm/67f966b2b9c6c0d234547e30/getMultSensorData?start_date=2025-04-17&end_date=2025-04-17

Content-Type: application/json
{

}

###
POST http://localhost:3000/farm/6802bc6da642e2e0cfd37cb0/addSensorData
Content-Type: application/json

{
    "temperature": 21,
    "height": 0,
    "camera": ""
}

###
DELETE http://localhost:3000/farm/6802bc6da642e2e0cfd37cb0/deleteSensorData
Content-Type: application/json

{
    
}

###
GET http://localhost:3000/farm/68029efecb480f3fb7c499cf/sensorImage

{

}

### System Level Tests
GET http://localhost:3000/farm/67faa966ef159124a495fc47/getSystemLevels
Content-Type: application/json

{

}

###
GET http://localhost:3000/farm/68029efecb480f3fb7c499cf/getAllSystemLevels
Content-Type: application/json

{

}

###
GET http://localhost:3000/farm/67f966b2b9c6c0d234547e30/getMultSystemLevels?start_date=2025-04-17&end_date=2025-04-17

Content-Type: application/json
{

}

###
POST http://localhost:3000/farm/6802bc6da642e2e0cfd37cb0/addSystemLevels
Content-Type: application/json

{
    "smart_shunt": {
        "battery_voltage": 12.2,
        "battery_current": 2.7,
        "battery_temp": 25,
        "power": 32.3,
        "state_of_charge": 75.4
    },
    "renogy_mppt": {
        "solar_panel_power": 0.6,
        "solar_panel_voltage": 11.5,
        "solar_panel_current": 1.2,
        "controller_temp": 20.7,
        "load_voltage": 12.2
    }
}

###
DELETE http://localhost:3000/farm/67faa966ef159124a495fc47/deleteSystemLevels
Content-Type: application/json

{
    
}

### LIft Schedule Tests 
POST http://localhost:3000/farm/cage
Content-Type: application/json

{
    "ids": "67edd17ad47abf534b7b45d8",
    "command": 1,
    "max_height": 10,
    "min_height": 5
}

###
POST http://localhost:3000/farm/cage/addActiveSchedule
Content-Type: application/json

{
    "farm_ids": [
        "67f966b2b9c6c0d234547e30", "67f966e7b9c6c0d234547e34"
    ],
    "schedule": [
        {
            "dates": ["2025-04-17 11:02:00"],
            "command": 1,
            "status": "pending"
        }
    ]
}

###
GET http://localhost:3000/farm/67f966b2b9c6c0d234547e30/getActiveLiftSchedule
Content-Type: application/json

{

}

###
GET http://localhost:3000/farm/67f966b2b9c6c0d234547e30/getAllActiveLiftSchedule
Content-Type: application/json

{

}

###
GET http://localhost:3000/farm/67f966b2b9c6c0d234547e30/getMultActiveLiftSchedule?start_date=2025-04-16&end_date=2025-04-17
Content-Type: application/json

{

}

###
POST http://localhost:3000/farm/cage/addArchiveSchedule
Content-Type: application/json

{
    
   "farm_ids": [
        "67f966b2b9c6c0d234547e30"
    ],
    "schedule": [
        {
            "dates": ["2025-04-18 15:23:00", "2025-04-14 18:56:00", "2025-04-20 17:35:00"],
            "command": 1,
            "duration": 4,
            "status": "pending",
            "lift_end_time": "2025-04-20 15:23:00"
        }
    ]
    
}

###
GET http://localhost:3000/farm/67f966b2b9c6c0d234547e30/getArchiveLiftSchedule
Content-Type: application/json

{

}

###
GET http://localhost:3000/farm/67f966e7b9c6c0d234547e34/getAllArchiveLiftSchedule
Content-Type: application/json

{

}

###
GET http://localhost:3000/farm/67f966e7b9c6c0d234547e34/getMultArchiveLiftSchedule?start_date=2025-04-17&end_date=2025-04-17
Content-Type: application/json

{

}

###
DELETE http://localhost:3000/farm/67f966b2b9c6c0d234547e30/deleteActiveLiftSchedule
Content-Type: application/json

{

}

###
DELETE http://localhost:3000/farm/67f966b2b9c6c0d234547e30/deleteArchiveLiftSchedule
Content-Type: application/json

{

}
