[project]
name = "sc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anyio>=4.9.0",
    "pymongo>=4.13.2",
    "pyserial>=3.5",
    "pytest>=8.4.1",
    "pyyaml>=6.0.2",
    "rich>=14.0.0",
    "trio>=0.30.0",
]
